# Generated by Django 5.0.14 on 2026-06-30 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=80)),
                ("titulo", models.CharField(max_length=160)),
                ("descricao", models.TextField(blank=True)),
                ("entidade_tipo", models.CharField(blank=True, max_length=80)),
                ("entidade_id", models.PositiveIntegerField(blank=True, null=True)),
                ("cliente_id", models.PositiveIntegerField(blank=True, null=True)),
                ("lead_id", models.PositiveIntegerField(blank=True, null=True)),
                ("oportunidade_id", models.PositiveIntegerField(blank=True, null=True)),
                ("pedido_id", models.PositiveIntegerField(blank=True, null=True)),
                ("produto_id", models.PositiveIntegerField(blank=True, null=True)),
                ("proxima_acao_id", models.PositiveIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_comerciais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "tipo", "criado_em"],
                        name="evt_log_emp_tipo_data_idx",
                    ),
                    models.Index(
                        fields=["empresa", "cliente_id", "criado_em"],
                        name="evt_log_emp_cli_data_idx",
                    ),
                    models.Index(
                        fields=["empresa", "oportunidade_id", "criado_em"],
                        name="evt_log_emp_op_data_idx",
                    ),
                    models.Index(
                        fields=["empresa", "pedido_id", "criado_em"],
                        name="evt_log_emp_ped_data_idx",
                    ),
                ],
            },
        ),
    ]
