# Generated by Django 5.0.14 on 2026-06-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=160)),
                ("ativa", models.BooleanField(default=True)),
                ("evento_disparador", models.CharField(max_length=80)),
                ("prioridade", models.PositiveIntegerField(default=100)),
                ("conditions", models.JSONField(blank=True, default=list)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["prioridade", "nome"],
            },
        ),
        migrations.CreateModel(
            name="AutomationExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("sucesso", "Sucesso"),
                            ("falha", "Falha"),
                            ("ignorada", "Ignorada"),
                        ],
                        default="sucesso",
                        max_length=20,
                    ),
                ),
                ("tempo_ms", models.PositiveIntegerField(default=0)),
                ("erro", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_execution_logs",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_executions",
                        to="eventos.eventlog",
                    ),
                ),
                (
                    "regra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="eventos.automationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["empresa", "ativa", "evento_disparador", "prioridade"],
                name="evt_auto_rule_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecutionlog",
            index=models.Index(
                fields=["empresa", "resultado", "criado_em"],
                name="evt_auto_exec_emp_result_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="automationexecutionlog",
            constraint=models.UniqueConstraint(
                fields=("evento", "regra"), name="unique_execucao_por_evento_regra"
            ),
        ),
    ]
