# Generated by Django 5.0.14 on 2026-06-30 18:05

from django.db import migrations, models


def atualizar_limites_saas(apps, schema_editor):
    Plano = apps.get_model("billing", "Plano")
    limites = {
        "start": {
            "limite_vendedores": 2,
            "limite_leads": 100,
            "limite_oportunidades": 50,
            "limite_recomendacoes_comerciais": 10,
            "permite_workspace_comercial": True,
        },
        "growth": {
            "limite_vendedores": 6,
            "limite_leads": 500,
            "limite_oportunidades": 250,
            "limite_recomendacoes_comerciais": 50,
            "permite_workspace_comercial": True,
        },
        "pro": {
            "limite_vendedores": 20,
            "limite_leads": 2000,
            "limite_oportunidades": 1000,
            "limite_recomendacoes_comerciais": 200,
            "permite_workspace_comercial": True,
        },
    }
    for codigo, dados in limites.items():
        Plano.objects.filter(codigo=codigo).update(**dados)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plano",
            name="limite_leads",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="plano",
            name="limite_oportunidades",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="plano",
            name="limite_recomendacoes_comerciais",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="plano",
            name="limite_vendedores",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="plano",
            name="permite_workspace_comercial",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(atualizar_limites_saas, migrations.RunPython.noop),
    ]
