# Generated by Django 5.0.14 on 2026-06-30 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proximaacao",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proximas_acoes",
                to="crm.cliente",
            ),
        ),
        migrations.AddField(
            model_name="proximaacao",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proximas_acoes",
                to="vendas.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="proximaacao",
            name="oportunidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proximas_acoes",
                to="crm.oportunidade",
            ),
        ),
    ]
